/**
 * Shared UI Components Export
 * Re-export commonly used Material-UI components and custom components
 */

export { sênhasTheme, ThemeProvider, CssBaseline } from './theme';

// Re-export Material-UI commons for convenience
export {
  Box,
  Container,
  Grid,
  Stack,
  Paper,
  Card,
  CardContent,
  CardHeader,
  Button,
  TextField,
  InputLabel,
  FormControl,
  Select,
  Checkbox,
  RadioGroup,
  Radio,
  FormGroup,
  FormControlLabel,
  Dialog,
  DialogTitle,
  DialogContent,
  DialogActions,
  Alert,
  Snackbar,
  CircularProgress,
  LinearProgress,
  Skeleton,
  Chip,
  Badge,
  Avatar,
  AvatarGroup,
  Typography,
  Divider,
  List,
  ListItem,
  ListItemText,
  ListItemIcon,
  ListItemButton,
  AppBar,
  Toolbar,
  IconButton,
  Menu,
  MenuItem,
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TablePagination,
  TableRow,
  Drawer,
  Breadcrumbs,
  Tab,
  Tabs,
} from '@mui/material';
